; generated by Slic3r 1.2.9 on 2015-12-23 at 12:27:09

; external perimeters extrusion width = 0.20mm
; perimeters extrusion width = 0.21mm
; infill extrusion width = 0.21mm
; solid infill extrusion width = 0.21mm
; top infill extrusion width = 0.21mm

; external perimeters extrusion width = 0.20mm
; perimeters extrusion width = 0.21mm
; infill extrusion width = 0.21mm
; solid infill extrusion width = 0.21mm
; top infill extrusion width = 0.21mm

M107
G28 X Y E; home all axes
G1 Z45
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 E24
T0 ; ensure we keep T0 active to prevent changing pressure
M400 ; wait for commands to complete
G1 E24 F1000.0 ; move extruder to midpoint
M400 ; wait for commands to complete
G91
G1 X-49 F1800.0 ; move over by x offset
G90
M400 ; wait for commands to complete
G1 E48 F1000.0 ; move extruder 0 into position
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 E24
G1 Z11.0 F480.000
 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 F240.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 E24
T0 ; ensure we keep T0 active to prevent changing pressure
M400 ; wait for commands to complete
G1 E24 F1000.0 ; move extruder to midpoint
M400 ; wait for commands to complete
G91
G1 X49 F1800.0 ; move over by x offset
G90
M400 ; wait for commands to complete
G1 E0 F1000.0 ; move extruder 1 into position
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 E24
G1 Z11.2 F480.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 F240.00000
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 E24
G1 X105.103 Y91.295 F480.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 E0
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
G1 X105.135 Y90.689 F240.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.199 Y90.243 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.338 Y89.652 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.538 Y89.079 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.795 Y88.529 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.108 Y88.008 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.472 Y87.523 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.885 Y87.077 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.341 Y86.677 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.836 Y86.325 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.364 Y86.026 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.92 Y85.783 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.498 Y85.598 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.093 Y85.474 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.389 Y85.436 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.005 Y85.403 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.611 Y85.438 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.908 Y85.474 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.502 Y85.598 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.08 Y85.783 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.636 Y86.026 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.164 Y86.325 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.659 Y86.677 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.115 Y87.077 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.528 Y87.523 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.892 Y88.008 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.205 Y88.529 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.462 Y89.079 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.662 Y89.652 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.801 Y90.243 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.879 Y90.845 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.897 Y91.305 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.848 Y92.057 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.74 Y92.655 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.57 Y93.238 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.341 Y93.8 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.056 Y94.336 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.717 Y94.84 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.329 Y95.306 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.894 Y95.73 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.418 Y96.107 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.905 Y96.434 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.362 Y96.705 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.794 Y96.92 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.207 Y97.075 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.607 Y97.168 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.0 Y97.2 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.393 Y97.168 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.793 Y97.075 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.206 Y96.92 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.638 Y96.705 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.095 Y96.434 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.582 Y96.107 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.106 Y95.73 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.671 Y95.306 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.283 Y94.84 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.944 Y94.336 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.659 Y93.8 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.43 Y93.238 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.26 Y92.655 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.152 Y92.057 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.103 Y91.295 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 Z11.4 F480.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 F240.00000
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 E24
T0 ; ensure we keep T0 active to prevent changing pressure
M400 ; wait for commands to complete
G1 E24 F1000.0 ; move extruder to midpoint
M400 ; wait for commands to complete
G91
G1 X-49 F1800.0 ; move over by x offset
G90
M400 ; wait for commands to complete
G1 E48 F1000.0 ; move extruder 0 into position
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 E24
G1 X56.103 Y91.095 F480.000
 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 E48
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X56.135 Y90.489 F240.000
 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.199 Y90.043 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.338 Y89.452 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.538 Y88.879 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.795 Y88.329 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.108 Y87.808 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.472 Y87.323 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.885 Y86.877 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.341 Y86.477 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.836 Y86.125 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.364 Y85.826 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.92 Y85.583 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X60.498 Y85.398 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X61.093 Y85.274 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X61.389 Y85.236 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.005 Y85.203 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.611 Y85.238 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.908 Y85.274 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X63.502 Y85.398 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.08 Y85.583 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.636 Y85.826 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.164 Y86.125 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.659 Y86.477 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.115 Y86.877 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.528 Y87.323 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.892 Y87.808 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.205 Y88.329 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.462 Y88.879 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.662 Y89.452 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.801 Y90.043 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.879 Y90.645 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.897 Y91.105 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.848 Y91.857 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.74 Y92.455 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.57 Y93.038 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.341 Y93.6 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.056 Y94.136 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.717 Y94.64 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.329 Y95.106 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.894 Y95.53 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.418 Y95.907 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.905 Y96.234 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.362 Y96.505 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X63.794 Y96.72 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X63.207 Y96.875 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.611 Y96.968 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.0 Y97.0 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X61.393 Y96.968 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X60.793 Y96.875 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X60.206 Y96.72 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.638 Y96.505 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.095 Y96.234 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.582 Y95.907 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.106 Y95.53 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.671 Y95.106 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.283 Y94.64 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.944 Y94.136 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.659 Y93.6 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.43 Y93.038 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.26 Y92.455 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.152 Y91.857 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.103 Y91.095 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
M106 S239.7
G1 Z11.6 F480.000
 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 F240.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 E24
T0 ; ensure we keep T0 active to prevent changing pressure
M400 ; wait for commands to complete
G1 E24 F1000.0 ; move extruder to midpoint
M400 ; wait for commands to complete
G91
G1 X49 F1800.0 ; move over by x offset
G90
M400 ; wait for commands to complete
G1 E0 F1000.0 ; move extruder 1 into position
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 E24
G1 X105.103 Y91.295 F480.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 E0
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
G1 X105.135 Y90.689 F240.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.199 Y90.243 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.338 Y89.652 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.538 Y89.079 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.795 Y88.529 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.108 Y88.008 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.472 Y87.523 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.885 Y87.077 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.341 Y86.677 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.836 Y86.325 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.364 Y86.026 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.92 Y85.783 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.498 Y85.598 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.093 Y85.474 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.389 Y85.436 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.005 Y85.403 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.611 Y85.438 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.908 Y85.474 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.502 Y85.598 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.08 Y85.783 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.636 Y86.026 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.164 Y86.325 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.659 Y86.677 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.115 Y87.077 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.528 Y87.523 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.892 Y88.008 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.205 Y88.529 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.462 Y89.079 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.662 Y89.652 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.801 Y90.243 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.879 Y90.845 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.897 Y91.305 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.848 Y92.057 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.74 Y92.655 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.57 Y93.238 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.341 Y93.8 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.056 Y94.336 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.717 Y94.84 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.329 Y95.306 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.894 Y95.73 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.418 Y96.107 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.905 Y96.434 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.362 Y96.705 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.794 Y96.92 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.207 Y97.075 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.607 Y97.168 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.0 Y97.2 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.393 Y97.168 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.793 Y97.075 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.206 Y96.92 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.638 Y96.705 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.095 Y96.434 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.582 Y96.107 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.106 Y95.73 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.671 Y95.306 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.283 Y94.84 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.944 Y94.336 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.659 Y93.8 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.43 Y93.238 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.26 Y92.655 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.152 Y92.057 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.103 Y91.295 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 Z11.8 F480.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 F240.00000
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 E24
T0 ; ensure we keep T0 active to prevent changing pressure
M400 ; wait for commands to complete
G1 E24 F1000.0 ; move extruder to midpoint
M400 ; wait for commands to complete
G91
G1 X-49 F1800.0 ; move over by x offset
G90
M400 ; wait for commands to complete
G1 E48 F1000.0 ; move extruder 0 into position
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 E24
G1 X56.103 Y91.095 F480.000
 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 E48
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X56.135 Y90.489 F240.000
 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.199 Y90.043 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.338 Y89.452 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.538 Y88.879 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.795 Y88.329 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.108 Y87.808 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.472 Y87.323 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.885 Y86.877 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.341 Y86.477 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.836 Y86.125 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.364 Y85.826 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.92 Y85.583 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X60.498 Y85.398 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X61.093 Y85.274 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X61.389 Y85.236 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.005 Y85.203 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.611 Y85.238 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.908 Y85.274 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X63.502 Y85.398 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.08 Y85.583 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.636 Y85.826 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.164 Y86.125 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.659 Y86.477 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.115 Y86.877 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.528 Y87.323 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.892 Y87.808 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.205 Y88.329 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.462 Y88.879 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.662 Y89.452 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.801 Y90.043 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.879 Y90.645 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.897 Y91.105 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.848 Y91.857 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.74 Y92.455 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.57 Y93.038 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.341 Y93.6 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.056 Y94.136 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.717 Y94.64 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.329 Y95.106 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.894 Y95.53 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.418 Y95.907 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.905 Y96.234 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.362 Y96.505 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X63.794 Y96.72 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X63.207 Y96.875 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.611 Y96.968 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.0 Y97.0 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X61.393 Y96.968 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X60.793 Y96.875 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X60.206 Y96.72 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.638 Y96.505 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.095 Y96.234 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.582 Y95.907 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.106 Y95.53 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.671 Y95.106 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.283 Y94.64 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.944 Y94.136 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.659 Y93.6 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.43 Y93.038 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.26 Y92.455 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.152 Y91.857 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.103 Y91.095 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 Z12.0 F480.000
 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 F240.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 E24
T0 ; ensure we keep T0 active to prevent changing pressure
M400 ; wait for commands to complete
G1 E24 F1000.0 ; move extruder to midpoint
M400 ; wait for commands to complete
G91
G1 X49 F1800.0 ; move over by x offset
G90
M400 ; wait for commands to complete
G1 E0 F1000.0 ; move extruder 1 into position
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 E24
G1 X105.103 Y91.295 F480.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 E0
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
G1 X105.135 Y90.689 F240.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.199 Y90.243 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.338 Y89.652 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.538 Y89.079 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.795 Y88.529 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.108 Y88.008 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.472 Y87.523 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.885 Y87.077 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.341 Y86.677 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.836 Y86.325 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.364 Y86.026 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.92 Y85.783 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.498 Y85.598 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.093 Y85.474 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.389 Y85.436 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.005 Y85.403 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.611 Y85.438 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.908 Y85.474 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.502 Y85.598 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.08 Y85.783 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.636 Y86.026 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.164 Y86.325 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.659 Y86.677 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.115 Y87.077 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.528 Y87.523 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.892 Y88.008 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.205 Y88.529 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.462 Y89.079 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.662 Y89.652 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.801 Y90.243 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.879 Y90.845 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.897 Y91.305 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.848 Y92.057 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.74 Y92.655 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.57 Y93.238 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.341 Y93.8 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.056 Y94.336 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.717 Y94.84 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.329 Y95.306 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.894 Y95.73 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.418 Y96.107 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.905 Y96.434 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.362 Y96.705 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.794 Y96.92 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.207 Y97.075 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.607 Y97.168 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.0 Y97.2 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.393 Y97.168 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.793 Y97.075 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.206 Y96.92 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.638 Y96.705 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.095 Y96.434 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.582 Y96.107 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.106 Y95.73 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.671 Y95.306 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.283 Y94.84 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.944 Y94.336 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.659 Y93.8 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.43 Y93.238 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.26 Y92.655 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.152 Y92.057 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.103 Y91.295 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 Z12.2 F480.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 F240.00000
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 E24
T0 ; ensure we keep T0 active to prevent changing pressure
M400 ; wait for commands to complete
G1 E24 F1000.0 ; move extruder to midpoint
M400 ; wait for commands to complete
G91
G1 X-49 F1800.0 ; move over by x offset
G90
M400 ; wait for commands to complete
G1 E48 F1000.0 ; move extruder 0 into position
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 E24
G1 X56.103 Y91.095 F480.000
 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 E48
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X56.135 Y90.489 F240.000
 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.199 Y90.043 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.338 Y89.452 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.538 Y88.879 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.795 Y88.329 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.108 Y87.808 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.472 Y87.323 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.885 Y86.877 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.341 Y86.477 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.836 Y86.125 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.364 Y85.826 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.92 Y85.583 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X60.498 Y85.398 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X61.093 Y85.274 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X61.389 Y85.236 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.005 Y85.203 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.611 Y85.238 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.908 Y85.274 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X63.502 Y85.398 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.08 Y85.583 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.636 Y85.826 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.164 Y86.125 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.659 Y86.477 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.115 Y86.877 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.528 Y87.323 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.892 Y87.808 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.205 Y88.329 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.462 Y88.879 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.662 Y89.452 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.801 Y90.043 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.879 Y90.645 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.897 Y91.105 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.848 Y91.857 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.74 Y92.455 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.57 Y93.038 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.341 Y93.6 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.056 Y94.136 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.717 Y94.64 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.329 Y95.106 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.894 Y95.53 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.418 Y95.907 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.905 Y96.234 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.362 Y96.505 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X63.794 Y96.72 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X63.207 Y96.875 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.611 Y96.968 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.0 Y97.0 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X61.393 Y96.968 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X60.793 Y96.875 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X60.206 Y96.72 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.638 Y96.505 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.095 Y96.234 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.582 Y95.907 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.106 Y95.53 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.671 Y95.106 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.283 Y94.64 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.944 Y94.136 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.659 Y93.6 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.43 Y93.038 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.26 Y92.455 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.152 Y91.857 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.103 Y91.095 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 Z12.4 F480.000
 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 F240.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 E24
T0 ; ensure we keep T0 active to prevent changing pressure
M400 ; wait for commands to complete
G1 E24 F1000.0 ; move extruder to midpoint
M400 ; wait for commands to complete
G91
G1 X49 F1800.0 ; move over by x offset
G90
M400 ; wait for commands to complete
G1 E0 F1000.0 ; move extruder 1 into position
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 E24
G1 X105.103 Y91.295 F480.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 E0
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
G1 X105.135 Y90.689 F240.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.199 Y90.243 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.338 Y89.652 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.538 Y89.079 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.795 Y88.529 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.108 Y88.008 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.472 Y87.523 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.885 Y87.077 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.341 Y86.677 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.836 Y86.325 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.364 Y86.026 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.92 Y85.783 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.498 Y85.598 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.093 Y85.474 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.389 Y85.436 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.005 Y85.403 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.611 Y85.438 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.908 Y85.474 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.502 Y85.598 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.08 Y85.783 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.636 Y86.026 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.164 Y86.325 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.659 Y86.677 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.115 Y87.077 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.528 Y87.523 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.892 Y88.008 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.205 Y88.529 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.462 Y89.079 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.662 Y89.652 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.801 Y90.243 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.879 Y90.845 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.897 Y91.305 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.848 Y92.057 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.74 Y92.655 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.57 Y93.238 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.341 Y93.8 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.056 Y94.336 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.717 Y94.84 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.329 Y95.306 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.894 Y95.73 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.418 Y96.107 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.905 Y96.434 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.362 Y96.705 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.794 Y96.92 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.207 Y97.075 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.607 Y97.168 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.0 Y97.2 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.393 Y97.168 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.793 Y97.075 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.206 Y96.92 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.638 Y96.705 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.095 Y96.434 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.582 Y96.107 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.106 Y95.73 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.671 Y95.306 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.283 Y94.84 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.944 Y94.336 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.659 Y93.8 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.43 Y93.238 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.26 Y92.655 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.152 Y92.057 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.103 Y91.295 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 Z12.6 F480.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 F240.00000
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 E24
T0 ; ensure we keep T0 active to prevent changing pressure
M400 ; wait for commands to complete
G1 E24 F1000.0 ; move extruder to midpoint
M400 ; wait for commands to complete
G91
G1 X-49 F1800.0 ; move over by x offset
G90
M400 ; wait for commands to complete
G1 E48 F1000.0 ; move extruder 0 into position
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 E24
G1 X56.103 Y91.095 F480.000
 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 E48
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X56.135 Y90.489 F240.000
 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.199 Y90.043 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.338 Y89.452 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.538 Y88.879 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.795 Y88.329 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.108 Y87.808 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.472 Y87.323 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.885 Y86.877 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.341 Y86.477 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.836 Y86.125 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.364 Y85.826 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.92 Y85.583 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X60.498 Y85.398 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X61.093 Y85.274 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X61.389 Y85.236 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.005 Y85.203 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.611 Y85.238 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.908 Y85.274 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X63.502 Y85.398 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.08 Y85.583 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.636 Y85.826 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.164 Y86.125 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.659 Y86.477 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.115 Y86.877 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.528 Y87.323 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.892 Y87.808 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.205 Y88.329 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.462 Y88.879 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.662 Y89.452 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.801 Y90.043 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.879 Y90.645 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.897 Y91.105 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.848 Y91.857 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.74 Y92.455 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.57 Y93.038 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.341 Y93.6 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.056 Y94.136 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.717 Y94.64 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.329 Y95.106 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.894 Y95.53 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.418 Y95.907 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.905 Y96.234 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.362 Y96.505 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X63.794 Y96.72 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X63.207 Y96.875 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.611 Y96.968 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.0 Y97.0 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X61.393 Y96.968 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X60.793 Y96.875 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X60.206 Y96.72 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.638 Y96.505 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.095 Y96.234 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.582 Y95.907 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.106 Y95.53 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.671 Y95.106 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.283 Y94.64 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.944 Y94.136 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.659 Y93.6 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.43 Y93.038 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.26 Y92.455 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.152 Y91.857 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.103 Y91.095 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 Z12.8 F480.000
 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 F240.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 E24
T0 ; ensure we keep T0 active to prevent changing pressure
M400 ; wait for commands to complete
G1 E24 F1000.0 ; move extruder to midpoint
M400 ; wait for commands to complete
G91
G1 X49 F1800.0 ; move over by x offset
G90
M400 ; wait for commands to complete
G1 E0 F1000.0 ; move extruder 1 into position
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 E24
G1 X105.103 Y91.295 F480.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 E0
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
G1 X105.135 Y90.689 F240.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.199 Y90.243 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.338 Y89.652 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.538 Y89.079 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.795 Y88.529 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.108 Y88.008 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.472 Y87.523 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.885 Y87.077 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.341 Y86.677 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.836 Y86.325 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.364 Y86.026 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.92 Y85.783 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.498 Y85.598 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.093 Y85.474 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.389 Y85.436 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.005 Y85.403 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.611 Y85.438 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.908 Y85.474 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.502 Y85.598 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.08 Y85.783 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.636 Y86.026 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.164 Y86.325 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.659 Y86.677 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.115 Y87.077 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.528 Y87.523 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.892 Y88.008 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.205 Y88.529 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.462 Y89.079 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.662 Y89.652 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.801 Y90.243 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.879 Y90.845 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.897 Y91.305 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.848 Y92.057 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.74 Y92.655 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.57 Y93.238 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.341 Y93.8 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.056 Y94.336 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.717 Y94.84 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.329 Y95.306 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.894 Y95.73 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.418 Y96.107 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.905 Y96.434 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.362 Y96.705 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.794 Y96.92 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.207 Y97.075 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.607 Y97.168 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.0 Y97.2 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.393 Y97.168 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.793 Y97.075 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.206 Y96.92 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.638 Y96.705 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.095 Y96.434 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.582 Y96.107 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.106 Y95.73 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.671 Y95.306 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.283 Y94.84 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.944 Y94.336 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.659 Y93.8 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.43 Y93.238 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.26 Y92.655 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.152 Y92.057 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.103 Y91.295 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 Z13.0 F480.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 F240.00000
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 E24
T0 ; ensure we keep T0 active to prevent changing pressure
M400 ; wait for commands to complete
G1 E24 F1000.0 ; move extruder to midpoint
M400 ; wait for commands to complete
G91
G1 X-49 F1800.0 ; move over by x offset
G90
M400 ; wait for commands to complete
G1 E48 F1000.0 ; move extruder 0 into position
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 E24
G1 X56.103 Y91.095 F480.000
 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 E48
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X56.135 Y90.489 F240.000
 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.199 Y90.043 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.338 Y89.452 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.538 Y88.879 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.795 Y88.329 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.108 Y87.808 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.472 Y87.323 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.885 Y86.877 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.341 Y86.477 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.836 Y86.125 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.364 Y85.826 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.92 Y85.583 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X60.498 Y85.398 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X61.093 Y85.274 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X61.389 Y85.236 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.005 Y85.203 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.611 Y85.238 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.908 Y85.274 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X63.502 Y85.398 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.08 Y85.583 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.636 Y85.826 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.164 Y86.125 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.659 Y86.477 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.115 Y86.877 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.528 Y87.323 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.892 Y87.808 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.205 Y88.329 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.462 Y88.879 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.662 Y89.452 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.801 Y90.043 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.879 Y90.645 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.897 Y91.105 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.848 Y91.857 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.74 Y92.455 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.57 Y93.038 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.341 Y93.6 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X67.056 Y94.136 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.717 Y94.64 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X66.329 Y95.106 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.894 Y95.53 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X65.418 Y95.907 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.905 Y96.234 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X64.362 Y96.505 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X63.794 Y96.72 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X63.207 Y96.875 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.611 Y96.968 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X62.0 Y97.0 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X61.393 Y96.968 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X60.793 Y96.875 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X60.206 Y96.72 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.638 Y96.505 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X59.095 Y96.234 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.582 Y95.907 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X58.106 Y95.53 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.671 Y95.106 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X57.283 Y94.64 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.944 Y94.136 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.659 Y93.6 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.43 Y93.038 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.26 Y92.455 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.152 Y91.857 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 X56.103 Y91.095 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 Z13.2 F480.000
 ; X offset of 56 Y offset of 90 and Z offset of 10.8 added.
G1 F240.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 E24
T0 ; ensure we keep T0 active to prevent changing pressure
M400 ; wait for commands to complete
G1 E24 F1000.0 ; move extruder to midpoint
M400 ; wait for commands to complete
G91
G1 X49 F1800.0 ; move over by x offset
G90
M400 ; wait for commands to complete
G1 E0 F1000.0 ; move extruder 1 into position
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 E24
G1 X105.103 Y91.295 F480.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 E0
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
G1 X105.135 Y90.689 F240.000
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.199 Y90.243 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.338 Y89.652 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.538 Y89.079 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.795 Y88.529 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.108 Y88.008 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.472 Y87.523 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.885 Y87.077 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.341 Y86.677 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.836 Y86.325 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.364 Y86.026 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.92 Y85.783 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.498 Y85.598 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.093 Y85.474 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.389 Y85.436 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.005 Y85.403 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.611 Y85.438 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.908 Y85.474 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.502 Y85.598 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.08 Y85.783 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.636 Y86.026 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.164 Y86.325 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.659 Y86.677 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.115 Y87.077 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.528 Y87.523 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.892 Y88.008 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.205 Y88.529 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.462 Y89.079 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.662 Y89.652 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.801 Y90.243 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.879 Y90.845 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.897 Y91.305 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.848 Y92.057 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.74 Y92.655 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.57 Y93.238 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.341 Y93.8 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X116.056 Y94.336 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.717 Y94.84 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X115.329 Y95.306 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.894 Y95.73 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X114.418 Y96.107 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.905 Y96.434 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X113.362 Y96.705 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.794 Y96.92 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X112.207 Y97.075 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.607 Y97.168 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X111.0 Y97.2 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X110.393 Y97.168 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.793 Y97.075 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X109.206 Y96.92 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.638 Y96.705 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X108.095 Y96.434 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.582 Y96.107 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X107.106 Y95.73 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.671 Y95.306 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X106.283 Y94.84 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.944 Y94.336 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.659 Y93.8 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.43 Y93.238 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.26 Y92.655 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.152 Y92.057 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 X105.103 Y91.295 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
G1 F240.00000
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 E24
M107
G28 X105.0  ; home X axis
 ; X offset of 105 Y offset of 90 and Z offset of 10.8 added.
M84     ; disable motors

; filament used = 0.9mm (0.0cm3)
; filament used = 1.1mm (0.0cm3)

; avoid_crossing_perimeters = 0
; bed_shape = 44.7535x4.70378,44.0166x9.35603,42.7975x13.9058,41.1095x18.3031,38.9711x22.5,36.4058x26.4503,33.4415x30.1109,30.1109x33.4415,26.4503x36.4058,22.5x38.9711,18.3031x41.1095,13.9058x42.7975,9.35603x44.0166,4.70378x44.7535,0x45,-4.70378x44.7535,-9.35603x44.0166,-13.9058x42.7975,-18.3031x41.1095,-22.5x38.9711,-26.4503x36.4058,-30.1109x33.4415,-33.4415x30.1109,-36.4058x26.4503,-38.9711x22.5,-41.1095x18.3031,-42.7975x13.9058,-44.0166x9.35603,-44.7535x4.70378,-45x0,-44.7535x-4.70378,-44.0166x-9.35603,-42.7975x-13.9058,-41.1095x-18.3031,-38.9711x-22.5,-36.4058x-26.4503,-33.4415x-30.1109,-30.1109x-33.4415,-26.4503x-36.4058,-22.5x-38.9711,-18.3031x-41.1095,-13.9058x-42.7975,-9.35603x-44.0166,-4.70378x-44.7535,0x-45,4.70378x-44.7535,9.35603x-44.0166,13.9058x-42.7975,18.3031x-41.1095,22.5x-38.9711,26.4503x-36.4058,30.1109x-33.4415,33.4415x-30.1109,36.4058x-26.4503,38.9711x-22.5,41.1095x-18.3031,42.7975x-13.9058,44.0166x-9.35603,44.7535x-4.70378,45x0
; bed_temperature = 0
; before_layer_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 3
; duplicate_distance = 6
; end_gcode = G28 X0  ; home X axis\nM84     ; disable motors\n
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0,0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #FFFFFF
; filament_diameter = 3
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 200%
; first_layer_speed = 4
; first_layer_temperature = 200
; gcode_arcs = 0
; gcode_comments = 0
; gcode_flavor = reprap
; infill_acceleration = 0
; infill_first = 0
; layer_gcode = 
; max_fan_speed = 100
; max_print_speed = 4
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 0.2,0.2
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; resolution = 0
; retract_before_travel = 0,0
; retract_layer_change = 0,0
; retract_length = 1,1
; retract_length_toolchange = 1,1
; retract_lift = 0,0
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 0,0
; retract_speed = 4,4
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slowdown_below_layer_time = 5
; spiral_vase = 0
; standby_temperature_delta = -5
; start_gcode = G28 ; home all axes\n\n
; temperature = 200
; threads = 2
; toolchange_gcode = 
; travel_speed = 8
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0,0
; z_offset = 0
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.2
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.2
; raft_layers = 0
; seam_position = aligned
; support_material = 0
; support_material_angle = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = pillars
; support_material_spacing = 2.5
; support_material_speed = 4
; support_material_threshold = 0
; xy_size_compensation = 0
; bottom_solid_layers = 3
; bridge_flow_ratio = 1
; bridge_speed = 4
; external_fill_pattern = rectilinear
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 4
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 99%
; fill_pattern = honeycomb
; gap_fill_speed = 4
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_overlap = 15%
; infill_speed = 4
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 4
; perimeters = 3
; small_perimeter_speed = 4
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 4
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 4
; top_solid_layers = 3

