; generated by Slic3r 1.2.9 on 2016-01-05 at 18:37:54

; external perimeters extrusion width = 0.20mm
; perimeters extrusion width = 0.34mm
; infill extrusion width = 0.34mm
; solid infill extrusion width = 0.34mm
; top infill extrusion width = 0.34mm

M107
G1 Z45
G1 E3.2
G28 X Y
G21
G1 X56 Y90 F1000


G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
T0 ; ensure we keep T0 active to prevent changing pressure
M400 ; wait for commands to complete
G1 E24 F1000.0 ; move extruder to midpoint
M400 ; wait for commands to complete
G1 Z0.1 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z0.2 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z0.3 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

M106 S173.4
G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z0.4 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z0.5 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z0.6 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z0.7 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z0.8 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z0.9 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z1.0 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z1.1 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z1.2 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z1.3 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z1.4 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z1.5 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z1.6 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z1.7 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z1.8 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z1.9 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z2.0 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z2.1 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z2.2 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z2.3 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z2.4 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z2.5 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z2.6 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z2.7 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z2.8 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z2.9 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z3.0 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z3.1 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z3.2 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z3.3 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z3.4 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z3.5 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z3.6 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z3.7 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z3.8 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z3.9 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z4.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z4.1 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z4.2 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z4.3 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z4.4 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z4.5 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z4.6 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z4.7 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z4.8 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z4.9 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z5.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z5.1 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z5.2 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z5.3 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z5.4 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z5.5 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z5.6 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z5.7 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z5.8 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z5.9 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z6.0 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z6.1 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z6.2 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z6.3 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z6.4 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z6.5 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z6.6 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z6.7 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z6.8 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z6.9 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z7.0 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z7.1 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z7.2 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z7.3 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z7.4 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z7.5 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z7.6 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z7.7 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z7.8 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z7.9 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z8.0 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z8.1 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z8.2 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z8.3 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z8.4 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z8.5 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z8.6 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z8.7 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z8.8 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z8.9 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.925 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z9.0 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z9.1 F480.000

G1 X94.211 Y90.097 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.266 Y88.899 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z9.2 F480.000

G1 X94.21 Y90.086 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.266 Y88.899 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z9.3 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z9.4 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z9.5 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z9.6 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z9.7 F480.000

G1 X94.207 Y90.032 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z9.8 F480.000

G1 X94.206 Y90.021 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z9.9 F480.000

G1 X94.205 Y90.0 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.263 Y88.924 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
G1 Z10.0 F480.000

G1 X94.205 Y89.993 F480.000

G1 E3.2 ; Move extruder to E1 position of 3.2
M400 ; wait for commands to complete
M42 P17 S255 ; turn extruder 1 on
M400 ; wait for commands to complete
G1 X94.264 Y88.912 F120.000

G92
M400 ; wait for commands to complete
M42 P17 S0 ; turn extruder 1 off
M107
G1 Z45
G1 E3.2
G28 X Y
G21
G1 X56 Y90 F1000
M84     ; disable motors

; filament used = 28.3mm (0.2cm3)

; avoid_crossing_perimeters = 0
; bed_shape = 44.7535x4.70378,44.0166x9.35603,42.7975x13.9058,41.1095x18.3031,38.9711x22.5,36.4058x26.4503,33.4415x30.1109,30.1109x33.4415,26.4503x36.4058,22.5x38.9711,18.3031x41.1095,13.9058x42.7975,9.35603x44.0166,4.70378x44.7535,0x45,-4.70378x44.7535,-9.35603x44.0166,-13.9058x42.7975,-18.3031x41.1095,-22.5x38.9711,-26.4503x36.4058,-30.1109x33.4415,-33.4415x30.1109,-36.4058x26.4503,-38.9711x22.5,-41.1095x18.3031,-42.7975x13.9058,-44.0166x9.35603,-44.7535x4.70378,-45x0,-44.7535x-4.70378,-44.0166x-9.35603,-42.7975x-13.9058,-41.1095x-18.3031,-38.9711x-22.5,-36.4058x-26.4503,-33.4415x-30.1109,-30.1109x-33.4415,-26.4503x-36.4058,-22.5x-38.9711,-18.3031x-41.1095,-13.9058x-42.7975,-9.35603x-44.0166,-4.70378x-44.7535,0x-45,4.70378x-44.7535,9.35603x-44.0166,13.9058x-42.7975,18.3031x-41.1095,22.5x-38.9711,26.4503x-36.4058,30.1109x-33.4415,33.4415x-30.1109,36.4058x-26.4503,38.9711x-22.5,41.1095x-18.3031,42.7975x-13.9058,44.0166x-9.35603,44.7535x-4.70378,45x0
; bed_temperature = 0
; before_layer_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 3
; duplicate_distance = 6
; end_gcode = G28 X0  ; home X axis\nM84     ; disable motors\n
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0,0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #FFFFFF
; filament_diameter = 3
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 0
; first_layer_speed = 2
; first_layer_temperature = 200
; gcode_arcs = 0
; gcode_comments = 0
; gcode_flavor = reprap
; infill_acceleration = 0
; infill_first = 0
; layer_gcode = 
; max_fan_speed = 100
; max_print_speed = 2
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 0.2,0.2
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; resolution = 0
; retract_before_travel = 0,0
; retract_layer_change = 1,1
; retract_length = 0,0
; retract_length_toolchange = 0,0
; retract_lift = 0,0
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 1,1
; retract_speed = 4,4
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slowdown_below_layer_time = 5
; spiral_vase = 0
; standby_temperature_delta = -5
; start_gcode = G28 ; home all axes\n\n
; temperature = 200
; threads = 2
; toolchange_gcode = 
; travel_speed = 8
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0,0
; z_offset = 0
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.1
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.1
; raft_layers = 0
; seam_position = aligned
; support_material = 0
; support_material_angle = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = pillars
; support_material_spacing = 2.5
; support_material_speed = 4
; support_material_threshold = 0
; xy_size_compensation = 0
; bottom_solid_layers = 1
; bridge_flow_ratio = 1
; bridge_speed = 2
; external_fill_pattern = rectilinear
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 2
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 99%
; fill_pattern = honeycomb
; gap_fill_speed = 2
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_overlap = 15%
; infill_speed = 2
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 2
; perimeters = 1
; small_perimeter_speed = 2
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 2
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 2
; top_solid_layers = 1

