; generated by Slic3r 1.2.9 on 2016-01-05 at 18:37:54

; external perimeters extrusion width = 0.20mm
; perimeters extrusion width = 0.34mm
; infill extrusion width = 0.34mm
; solid infill extrusion width = 0.34mm
; top infill extrusion width = 0.34mm

M107
G1 Z45
G1 E3.2
G28 X Y
G21
G1 X56 Y90 F1000


G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
T0 ; ensure we keep T0 active to prevent changing pressure
M400 ; wait for commands to complete
G1 E24 F1000.0 ; move extruder to midpoint
M400 ; wait for commands to complete
