; generated by Slic3r 1.2.9 on 2015-12-09 at 18:08:31

; external perimeters extrusion width = 0.50mm
; perimeters extrusion width = 0.85mm
; infill extrusion width = 1.02mm
; solid infill extrusion width = 0.85mm
; top infill extrusion width = 0.85mm

G28 Z
G28 E
G28 X Y
G1 E10 F100
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z12.6 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X14.178 Y59.180 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X25.178 Y59.180 F600.000
G1 X27.389 Y59.577
G1 X29.323 Y60.718 F600.000
G1 X30.741 Y62.461
G1 X31.535 Y65.537
G1 X31.535 Y76.537
G1 X31.138 Y78.748
G1 X29.997 Y80.683
G1 X28.254 Y82.101
G1 X25.178 Y82.895
G1 X14.178 Y82.895
G1 X11.967 Y82.498
G1 X10.032 Y81.357
G1 X8.615 Y79.614
G1 X7.821 Y76.537
G1 X7.821 Y65.537
G1 X8.217 Y63.327
G1 X9.358 Y61.392
G1 X11.101 Y59.974
G1 X14.105 Y59.199
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y76.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y76.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y74.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y74.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y73.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y73.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y71.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y71.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y70.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y70.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y68.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y68.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y67.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y67.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y65.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y65.787 F600.000
M106 S255
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z12.8 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X25.178 Y76.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y76.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y74.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y74.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y73.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y73.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y71.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y71.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y70.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y70.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y68.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y68.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y67.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y67.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y65.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y65.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z13.0 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X25.178 Y76.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y76.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y74.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y74.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y73.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y73.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y71.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y71.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y70.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y70.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y68.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y68.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y67.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y67.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y65.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y65.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z13.2 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X25.178 Y76.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y76.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y74.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y74.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y73.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y73.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y71.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y71.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y70.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y70.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y68.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y68.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y67.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y67.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y65.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y65.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z13.4 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X25.178 Y76.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y76.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y74.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y74.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y73.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y73.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y71.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y71.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y70.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y70.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y68.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y68.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y67.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y67.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y65.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y65.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z13.6 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X25.178 Y76.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y76.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y74.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y74.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y73.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y73.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y71.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y71.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y70.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y70.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y68.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y68.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y67.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y67.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y65.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y65.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z13.8 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X24.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X24.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X23.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X23.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X21.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X21.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X20.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X20.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X18.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X18.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X17.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X17.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X15.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X15.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X14.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z14.0 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X24.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X24.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X23.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X23.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X21.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X21.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X20.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X20.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X18.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X18.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X17.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X17.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X15.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X15.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X14.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z14.2 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X24.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X24.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X23.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X23.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X21.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X21.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X20.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X20.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X18.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X18.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X17.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X17.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X15.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X15.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X14.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z14.4 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X24.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X24.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X23.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X23.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X21.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X21.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X20.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X20.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X18.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X18.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X17.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X17.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X15.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X15.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X14.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z14.6 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X24.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X24.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X23.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X23.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X21.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X21.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X20.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X20.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X18.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X18.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X17.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X17.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X15.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X15.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X14.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z14.8 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X24.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X24.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X23.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X23.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X21.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X21.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X20.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X20.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X18.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X18.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X17.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X17.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X15.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X15.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X14.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z15.0 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X25.178 Y76.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y76.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y74.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y74.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y73.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y73.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y71.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y71.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y70.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y70.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y68.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y68.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y67.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y67.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y65.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y65.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z15.2 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X25.178 Y76.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y76.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y74.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y74.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y73.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y73.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y71.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y71.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y70.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y70.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y68.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y68.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y67.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y67.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y65.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y65.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z15.4 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X25.178 Y76.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y76.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y74.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y74.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y73.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y73.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y71.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y71.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y70.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y70.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y68.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y68.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y67.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y67.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y65.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y65.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z15.6 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X25.178 Y76.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y76.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y74.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y74.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y73.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y73.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y71.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y71.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y70.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y70.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y68.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y68.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y67.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y67.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y65.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y65.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z15.8 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X25.178 Y76.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y76.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y74.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y74.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y73.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y73.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y71.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y71.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y70.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y70.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y68.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y68.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y67.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y67.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y65.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y65.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z16.0 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X25.178 Y76.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y76.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y74.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y74.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y73.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y73.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y71.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y71.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y70.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y70.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y68.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y68.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y67.287 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y67.287 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X25.178 Y65.787 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.178 Y65.787 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z16.2 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X24.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X24.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X23.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X23.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X21.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X21.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X20.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X20.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X18.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X18.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X17.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X17.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X15.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X15.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X14.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z16.4 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X24.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X24.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X23.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X23.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X21.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X21.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X20.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X20.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X18.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X18.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X17.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X17.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X15.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X15.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X14.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z16.6 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X24.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X24.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X23.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X23.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X21.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X21.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X20.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X20.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X18.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X18.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X17.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X17.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X15.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X15.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X14.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z16.8 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X24.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X24.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X23.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X23.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X21.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X21.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X20.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X20.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X18.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X18.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X17.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X17.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X15.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X15.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X14.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z17.0 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X24.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X24.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X23.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X23.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X21.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X21.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X20.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X20.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X18.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X18.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X17.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X17.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X15.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X15.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X14.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 Z17.2 F1080.000 ; Extruder 0 Z Offset of 12.4 added.
G1 X24.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X24.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X23.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X23.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X21.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X21.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X20.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X20.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X18.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X18.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X17.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X17.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X15.928 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X15.928 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off
G1 X14.428 Y76.537 F1080.000
G1 E20 F100
M400 ; wait for commands to complete
M42 P16 S255 ; turn extruder 0 on
G1 X14.428 Y65.537 F600.000
G1 F1800.00000
M400 ; wait for commands to complete
M42 P16 S0 ; turn extruder 0 off

; filament used = 48.0mm (0.3cm3)

; avoid_crossing_perimeters = 0
; bed_shape = -6.87x47.6,120.13x47.6,120.13x133,-6.87x133
; bed_temperature = 0
; before_layer_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 1
; duplicate_distance = 6
; end_gcode = 
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0,0x0
; extrusion_axis = E
; extrusion_multiplier = 1,1
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #FFFFFF;#FFFFFF
; filament_diameter = 3,3
; first_layer_acceleration = 0
; first_layer_bed_temperature = 5
; first_layer_extrusion_width = 200%
; first_layer_speed = 70%
; first_layer_temperature = 205,200
; gcode_arcs = 0
; gcode_comments = 0
; gcode_flavor = reprap
; infill_acceleration = 0
; infill_first = 0
; layer_gcode = 
; max_fan_speed = 100
; max_print_speed = 60
; max_volumetric_speed = 60
; min_fan_speed = 35
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 0.5,0.5
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; resolution = 0
; retract_before_travel = 2,2
; retract_layer_change = 1,1
; retract_length = 1,1
; retract_length_toolchange = 10,10
; retract_lift = 0,0
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 0,0
; retract_speed = 30,30
; skirt_distance = 6
; skirt_height = 1
; skirts = 1
; slowdown_below_layer_time = 30
; spiral_vase = 0
; standby_temperature_delta = -5
; start_gcode = G28
; temperature = 200,200
; threads = 2
; toolchange_gcode = 
; travel_speed = 18
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0,0
; z_offset = 0
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.2
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.2
; raft_layers = 0
; seam_position = aligned
; support_material = 0
; support_material_angle = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 0
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_threshold = 0
; xy_size_compensation = 0
; bottom_solid_layers = 3
; bridge_flow_ratio = 1
; bridge_speed = 60
; external_fill_pattern = rectilinear
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 60
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 40%
; fill_pattern = honeycomb
; gap_fill_speed = 60
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_overlap = 15%
; infill_speed = 60
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 60
; perimeters = 3
; small_perimeter_speed = 60
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 60
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 60
; top_solid_layers = 3
